### ISSUE TITLE
Depreciated - But how to present to a user via radio browser

### ISSUE THREAD

**Issue by psyciknz** [giachello/netradio#9]
Hi.

I've got a script I run that takes a radio station name from a input helper and uses the selected name and an if statement to match it to a url.   But it's very clunky.  If I want to add a new station I hjave to update the input helper and the script element.

I almost though of writing my own custom components then saw yours.

Is there a way with teh radio browser - to have a config file with this wonderful format of your:
```
netradio:
  radios: 
    - url: 'http://streams.greenhost.nl:8080/jazz'
      name: Concertzender Jazz
```
and use that to present to the users the station names and use the url to pass to a media_player?

I'm hoping that with your radio-browser comment, that maybe you have done some of this ground work to figure that out.
